// File generated by FlutterFire CLI / manual export from google-services.json & GoogleService-Info.plist.
// Do not modify directly.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3g0-D5xFffHPFfq8hhjZ1rI4G8i4WwcU',
    appId: '1:637715249195:android:25fc63d66ef988e756126e',
    messagingSenderId: '637715249195',
    projectId: 'at-tayyibun-e3f79',
    storageBucket: 'at-tayyibun-e3f79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Sz9xVuEPFqHwLxf_eJ18eYKnhSYPPl0',
    appId: '1:637715249195:ios:44b1cfac12e7952556126e',
    messagingSenderId: '637715249195',
    projectId: 'at-tayyibun-e3f79',
    storageBucket: 'at-tayyibun-e3f79.firebasestorage.app',
    iosBundleId: 'com.attayyibun.attayyibun',
  );
}
